### ISSUE TITLE
UI not work after install

### ISSUE THREAD

**Issue by lahorenc** [snax44/wireguard-ui-setup#2]
I did lots your installs, and now WG UI on Ubuntu 20.04 not work.
Can you check this please?
Regards,
Lahor

**Comment by snax44** [comment]
Can yoi tell me more,

What's the oitpit of `netstat -plantu` and `iptables -L -n` ?

How are you trying to access the WebUI ?

**Comment by lahorenc** [comment]
Hi

Wireguard is work.

Can not access to web gui after new installation. Trying on 2 servers and same problem.

**Comment by snax44** [comment]
Please answer my questions, then I'll try to help you

**Comment by lahorenc** [comment]
Wireguard work, can not connect to UI with port 5000. Like as usualy. This can be go problem on new install or something like this.

**Comment by snax44** [comment]
Again,


What are the outputs of `netstat -plantu` and `iptables -L -n` ?

**Comment by nigelfer2020** [comment]
> Wireguard work, can not connect to UI with port 5000. Like as usualy. This can be go problem on new install or something like this.

Easy fix:
Connect to SSH:
nano  /etc/systemd/system/wgui_http.service
and then remove "-bind-address 127.0.0.1:5000" and save it.
then re-try to open via web.

also make sure 5000 port is open in firewall
sudo ufw allow 5000/udp
sudo ufw allow 5000/tcp

Let me know if its worked?

**Comment by lahorenc** [comment]
Yes, it work's now after removing -bind-address 127.0.0.1:5000 and restart server.
Tnx!

**Comment by snax44** [comment]
Wireguard-ui is bind on localhost for security reasons, there are no reasons to expose it on the network.
Your were supposed to access it through an ssh tunnel.
Or eventually behind nginx proxy with TLS certificates.
